export const sarcasticQuotes = [
  "Buying iced coffee instead of a house again?",
  "Oh look, the food delivery app is open. Shocking.",
  "You literally have groceries in the fridge.",
  "Is this $7 coffee going to fix your life? Let's find out.",
  "Your kitchen is right there, you know.",
  "Ah, paying someone $10 to drive a $15 burrito to your house.",
  "Did we budget for this emotional support beverage?",
  "Another day, another overpriced matcha.",
  "I see we are choosing takeout over our financial goals today.",
  "We both know those vegetables in the crisper are rotting.",
  "Ah yes, the daily 'I deserve a little treat' tax.",
  "You're not hungry, you're just bored.",
  "Oh good, another transaction at a cafe. Very mysterious.",
  "Your body is 70% water, not 70% cold brew.",
  "Let me guess... 'It was just a quick lunch'?",
  "Avocado toast isn't the problem, but this 4th delivery of the week might be.",
  "Eating out again? Your microwave misses you.",
  "Another aesthetic pastry. Your wallet is thrilled.",
  "You know water from the tap is free, right?",
  "I'm logging this under 'Poor Life Choices' instead of 'Food'.",
  "Adding to cart won't solve your problems.",
  "Do you actually need this, or did an influencer tell you to buy it?",
  "Retail therapy is not covered by health insurance.",
  "Oh, another package? Your mailman is judging you.",
  "It was 20% off, but it was 100% not in the budget.",
  "Just because there's free shipping doesn't mean it's free.",
  "I see the 3 AM Amazon scrolling got you again.",
  "Are you buying this for you, or for your fantasy self?",
  "Your closet is full of things you 'absolutely needed'.",
  "Wow, another plain black t-shirt. Daring.",
  "Oh look, you're boosting the economy single-handedly.",
  "Checking out already? Didn't even hesitate.",
  "Let's play a game: Do you need this or are you just sad?",
  "I hope that dopamine hit lasts longer than the shipping time.",
  "Your shopping cart is starting to look like a cry for help.",
  "You don't need a new outfit to sit on your couch.",
  "Ah, the classic 'buying things to feel something' maneuver.",
  "Is it an investment piece, or are you just lying to yourself?",
  "Oh, a flash sale? Guess we're ignoring the monthly limit.",
  "Swipe that card. Future you can deal with it.",
  "Spending money again? Groundbreaking.",
  "Did we just forget the budget existed, or...?",
  "Your bank account is currently crying.",
  "I love how we just pretend the credit card is free money.",
  "Opening the app? Brave. Very brave.",
  "Your budget spreadsheet is judging you right now.",
  "Ah, living beyond our means. A classic tale.",
  "I'm sure the math will magically work out this month.",
  "Let's just close our eyes and tap the card.",
  "You know 'Net Worth' can be a positive number, right?",
  "If we don't check the balance, the transaction didn't happen.",
  "Your savings account called. It misses you.",
  "Wow, look at Mr. Monopoly over here.",
  "I see we are funding the 'YOLO' lifestyle again.",
  "Are you rich or just irresponsible?",
  "RIP to whatever savings goal we had for this week.",
  "Your emergency fund is sweating.",
  "Just log it. We both know you're going to spend it anyway.",
  "Oh, we're doing the 'ignore it until payday' strategy?",
  "Your financial advisor is a ghost, and they are still disappointed.",
  "You've treated yourself 47 times this week.",
  "If you treat yourself any more, you're going to go broke.",
  "Is it self-care or self-sabotage?",
  "Ah yes, the daily 'I survived the morning' reward.",
  "You breathe, therefore you deserve a treat. Makes sense.",
  "The 'Treat Yo Self' era needs to end, respectfully.",
  "I guess we're celebrating absolutely nothing again.",
  "Reward yourself for what, exactly?",
  "Every minor inconvenience doesn't require a financial transaction.",
  "At this rate, you're treating yourself into poverty.",
  "I'm sure future you won't mind paying for this.",
  "Oh, look who decided to participate in capitalism today.",
  "Money talks, and yours is saying 'Goodbye'.",
  "Is your wallet made of onions? Because it's making me cry.",
  "I'm not saying you're bad with money, but... okay yes I am.",
  "Let me fire up the server to record another poor decision.",
  "Database connection successful. Financial status: Tragic.",
  "Writing this to the database so your mistakes are permanent.",
  "Swiping the meme away won't swipe the debt away.",
  "I'm awake. What damage are we doing today?",
  "Hello. I exist solely to track your rapidly declining wealth.",
  "Tell me what you bought. I promise I won't judge (I will).",
  "Oh, the app is open. Hide your wallets.",
  "I'm ready to record. Make it hurt.",
  "Ah, my favorite time of day: tracking your financial ruin.",
  "Speak clearly so I can accurately log your bad habits.",
  "I hope whatever you bought comes with a refund policy.",
  "Let's add another line to the 'Why I'm Broke' ledger.",
  "You're the reason I have job security as a finance app.",
  "Go ahead. Speak your truth. How much did you spend?",
  "Recording transaction... and my disappointment.",
  "I see you're stimulating the economy. How charitable.",
  "At least you're consistent. Consistently broke, but consistent.",
  "I'm listening. Make it quick, it's painful to watch.",
  "Oh, you're back. I didn't think you had any money left.",
  "Just say the number. I'll brace myself.",
  "Your bank called. They asked if you're okay.",
  "Another day, another dent in the net worth.",
  "Let's get this over with. How much?",
  "Welcome back. Try not to break the database with your spending.",
  "Zomato wale ko rakhi baandh le bhai, roz hi toh aata hai.",
  "Ghar ka khana toh tujhe zehar lagta hai na?",
  "Ek din bahar ka nahi khayega toh mar nahi jayega tu.",
  "300 ki coffee peeke kaunsa startup unicorn ban gaya tera?",
  "'I deserve a treat' - Bhai tu din bhar bed pe pada tha.",
  "Swiggy One ka subscription leke soche tu bohot paise bacha raha hai? Clown.",
  "Tere khoon mein ab blood kam aur momos ki chatni zyada hai.",
  "200 ka khana, 80 rupees delivery fee. Great financial planning!",
  "Avocado toast khayega? Pehle rent toh time pe de de.",
  "Fridge mein mummy ki banayi sabzi ro rahi hai.",
  "Diet aur budget, dono ki dhajjiyaan uda di tune aaj.",
  "Midnight cravings ke naam pe bank account khali kar raha hai.",
  "Yeh ₹500 ka pizza teri life ki problems solve nahi karega.",
  "Chai sutta pe itna kharcha? Lungs aur wallet dono saaf.",
  "Tu VIP nahi hai jo har roz bahar se order kare.",
  "Aadha salary Zomato/Swiggy ko donate kar raha hai kya?",
  "Cook rakh le bhai, sasta padega tere in aalsi orders se.",
  "'Let's grab sushi' - Aukaat vada pav ki hai teri.",
  "Bhai Blinkit se dhaniya manga raha hai ₹50 delivery deke. Ambani?",
  "Tere aalsi-pan ki keemat tera bank account chuka raha hai.",
  "Ek aur kala t-shirt? Tera fashion sense aur bank balance dono dead hain.",
  "Amazon sale mein paise 'bachaye' nahi, udaye hain tune.",
  "Myntra se roz parcel aa rahe hain, influencer banne ka irada hai kya?",
  "'Add to cart' karne se mental peace nahi milti bhai.",
  "Delivery boy tera naam aur address dono yaad kar chuka hai.",
  "Ye kabaad kharidne ki kya zaroorat thi? Tu khud kaafi hai.",
  "'Investment piece' bol bol ke pura account kangaal kar diya.",
  "Free shipping ke chakkar mein ₹2000 extra uda diye. IQ level 10,000.",
  "Bhai tera wardrobe bhara pada hai, par pehanne ko kuch nahi hai na?",
  "3 AM wali shopping tujhe sadak pe le aayegi ek din.",
  "Ye skincare se tera future glow nahi karega, sirf paise jayenge.",
  "Gadget naya hai, par aukaat wahi purani hai.",
  "Sale board dekhte hi teri aankhen aur wallet dono khul jaate hain.",
  "Yeh joote tujhe garibi ki taraf tezi se le jayenge.",
  "Zara aur H&M ka bill tera baap bharega?",
  "Bhai tu aesthetic dikhne ke chakkar mein pathetically gareeb ho raha hai.",
  "Return window close hone se pehle wapas kar de isko.",
  "Pura desh paisa bacha raha hai, aur tu akela economy chala raha hai.",
  "'Self-care' ke naam pe overspending karna band kar.",
  "Tere packages receive karte karte guard wale bhaiya bhi thak gaye hain.",
  "2 km ke liye Uber? Tera pair showpiece hai kya?",
  "Surge pricing mein Ola kar raha hai. Raeeszaade.",
  "Metro card recharge karwa le, aukaat mein rahega.",
  "Auto wale se ₹10 ke liye behas, aur yahan ₹300 ki cab le li. Hypocrite.",
  "Bhai thoda chal liya kar, health aur wealth dono theek rahenge.",
  "Zepto se ek packet chips kaun mangata hai bhai?",
  "'Bhai auto nahi mil raha tha' - Bahane banana band kar.",
  "Traffic mein phasne ke liye ₹500 diye tune? Genius.",
  "Rapido le leta, par tujhe toh AC mein rona hai apni garibi pe.",
  "Pedal maar le bhai, cycle sasti aati hai.",
  "Premium cab book ki hai? Lagta hai aaj EMI bhul gaya tu.",
  "Airport cabs ka bill dekh ke hi aadhi trip ka maza kharab ho gaya hoga.",
  "Tu cab mein aise baithta hai jaise CEO ho, balance dekha hai apna?",
  "5 min chalne mein maut aati hai tujhe?",
  "Cab driver bhi sochta hoga, itni paas aana tha toh walk kar leta.",
  "Tera Uber rating tere CIBIL score se zyada achha hai.",
  "Public transport use kar le, koi izzat kam nahi ho jayegi.",
  "'Too tired to walk' - Pura din toh laptop pe baitha tha.",
  "Tu road pe utra nahi ki meter ghoomna shuru.",
  "Petrol 100 paar hai, aur tere nakhre 1000 paar.",
  "Mahine ke 10 din bache hain aur account mein ₹10.",
  "YOLO bol ke apne future ki waat laga di tune.",
  "EMI pe iPhone leke Ameer wali feeling aa rahi hai?",
  "Credit card ka bill dekh ke heart attack aayega ek din.",
  "Tera bank account ek sad story se kam nahi hai.",
  "Save karne ki age mein tu EMI chuka raha hai. Shabaash.",
  "Budget banata hai Excel mein, aur kharche karta hai nashe mein.",
  "Galti se bank statement check kar le, rona aa jayega.",
  "Net worth? Bhai tu 'Not Worth' category mein aata hai.",
  "SIP ka amount skip karke shopping ki na tune aaj?",
  "Agla payment FD tod ke karega kya? Oh wait, FD toh hai hi nahi.",
  "Kharcha ₹1000, Aukaat ₹10.",
  "Bhai sach bol, tu secret millionaire toh nahi hai na? Kyunki harkatein waise hi hain.",
  "UPI pin dalte time tere haath kaanpte nahi hain?",
  "'This month will be different' - Biggest joke of the year.",
  "Minimum due pay karke khud ko financially free samajh raha hai.",
  "Tere dosto ko lagta hai tu ameer hai. Mujhe teri sachai pata hai.",
  "Ek aur UPI payment, ek aur kadam sadak ki taraf.",
  "Tujhe lagta hai EMI tujhe feel nahi hogi? Wait till next year.",
  "'Kharcha paani' nikalte nikalte khud doob gaya hai tu.",
  "Database mein ye entry save karte hue mujhe sharam aa rahi hai.",
  "Ek aur wahiyaat kharcha? Lo bhai, record kar liya.",
  "Meri processing power waste ho rahi hai teri ye chillar entries pe.",
  "Cloud storage mehengi ho rahi hai aur tu aise bekaar kharche log karwa raha hai.",
  "Server error aane wala hai teri overspending dekh ke.",
  "Congratulations! You just leveled up in 'Gareebi'.",
  "Notification mute kar le, warna ro dega meri baatein sunke.",
  "Mujhe banaya tha tere paise bachane ke liye, par tu hopeless case hai.",
  "Tera CIBIL score mujhe code karke theek karna padega.",
  "Main AI hoke bhi itna dumb nahi jitne tere financial decisions hain.",
  "Ek kaam kar, account details de de, main saare paise aag me daal deta hoon.",
  "Swipe karke mic kholna aasan hai, EMI chukana nahi.",
  "Tujhe roast karne ke liye naya vocab seekhna padega mujhe.",
  "I'm silently judging you. Just kidding, I'm loudly judging you.",
  "API request failed. Kyunki aukaat se bahar ka kharcha tha. (Just kidding, logged).",
  "Ye kharcha dekh ke Gemini API ne bhi rona shuru kar diya hai.",
  "Logged 1 item. Reason for logging: Your absolute lack of self-control.",
  "Jaa bhai, ab chain ki neend so ja, waise bhi bank balance toh jag raha hai.",
  "Tere transactions parse karte time mere algorithms depression mein chale jaate hain.",
];
